// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file common/split-billing.proto (package common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message common.SplitBillingModel
 */
export class SplitBillingModel extends Message<SplitBillingModel> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: string group_id = 4;
   */
  groupId = "";

  /**
   * @generated from field: int64 amount = 5;
   */
  amount = protoInt64.zero;

  /**
   * @generated from field: string advance_payer_id = 6;
   */
  advancePayerId = "";

  /**
   * @generated from field: string split_billing_type = 7;
   */
  splitBillingType = "";

  /**
   * @generated from field: repeated common.SplitBillingModel.Member members = 8;
   */
  members: SplitBillingModel_Member[] = [];

  /**
   * @generated from field: string status = 9;
   */
  status = "";

  constructor(data?: PartialMessage<SplitBillingModel>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "common.SplitBillingModel";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "advance_payer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "split_billing_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "members", kind: "message", T: SplitBillingModel_Member, repeated: true },
    { no: 9, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SplitBillingModel {
    return new SplitBillingModel().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SplitBillingModel {
    return new SplitBillingModel().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SplitBillingModel {
    return new SplitBillingModel().fromJsonString(jsonString, options);
  }

  static equals(a: SplitBillingModel | PlainMessage<SplitBillingModel> | undefined, b: SplitBillingModel | PlainMessage<SplitBillingModel> | undefined): boolean {
    return proto3.util.equals(SplitBillingModel, a, b);
  }
}

/**
 * @generated from message common.SplitBillingModel.Member
 */
export class SplitBillingModel_Member extends Message<SplitBillingModel_Member> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<SplitBillingModel_Member>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "common.SplitBillingModel.Member";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SplitBillingModel_Member {
    return new SplitBillingModel_Member().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SplitBillingModel_Member {
    return new SplitBillingModel_Member().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SplitBillingModel_Member {
    return new SplitBillingModel_Member().fromJsonString(jsonString, options);
  }

  static equals(a: SplitBillingModel_Member | PlainMessage<SplitBillingModel_Member> | undefined, b: SplitBillingModel_Member | PlainMessage<SplitBillingModel_Member> | undefined): boolean {
    return proto3.util.equals(SplitBillingModel_Member, a, b);
  }
}

