// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts"
// @generated from file connection/connection.proto (package warican.api.connection, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { ConnectionGetV1_Response } from "./connection_pb.js";

/**
 * @generated from rpc warican.api.connection.Connection.GetV1
 */
export const getV1 = {
  localName: "getV1",
  name: "GetV1",
  kind: MethodKind.Unary,
  I: Empty,
  O: ConnectionGetV1_Response,
  service: {
    typeName: "warican.api.connection.Connection"
  }
} as const;
