// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file connection/connection.proto (package warican.api.connection, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { UserModel } from "../common/user_pb.js";

/**
 * @generated from message warican.api.connection.ConnectionGetV1
 */
export class ConnectionGetV1 extends Message<ConnectionGetV1> {
  constructor(data?: PartialMessage<ConnectionGetV1>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "warican.api.connection.ConnectionGetV1";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConnectionGetV1 {
    return new ConnectionGetV1().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConnectionGetV1 {
    return new ConnectionGetV1().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConnectionGetV1 {
    return new ConnectionGetV1().fromJsonString(jsonString, options);
  }

  static equals(a: ConnectionGetV1 | PlainMessage<ConnectionGetV1> | undefined, b: ConnectionGetV1 | PlainMessage<ConnectionGetV1> | undefined): boolean {
    return proto3.util.equals(ConnectionGetV1, a, b);
  }
}

/**
 * @generated from message warican.api.connection.ConnectionGetV1.Response
 */
export class ConnectionGetV1_Response extends Message<ConnectionGetV1_Response> {
  /**
   * @generated from field: repeated common.UserModel connected_users = 1;
   */
  connectedUsers: UserModel[] = [];

  constructor(data?: PartialMessage<ConnectionGetV1_Response>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "warican.api.connection.ConnectionGetV1.Response";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "connected_users", kind: "message", T: UserModel, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConnectionGetV1_Response {
    return new ConnectionGetV1_Response().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConnectionGetV1_Response {
    return new ConnectionGetV1_Response().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConnectionGetV1_Response {
    return new ConnectionGetV1_Response().fromJsonString(jsonString, options);
  }

  static equals(a: ConnectionGetV1_Response | PlainMessage<ConnectionGetV1_Response> | undefined, b: ConnectionGetV1_Response | PlainMessage<ConnectionGetV1_Response> | undefined): boolean {
    return proto3.util.equals(ConnectionGetV1_Response, a, b);
  }
}

