// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file wallet/wallet.proto (package warican.api.wallet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { WalletDepositV1_Request, WalletDepositV1_Response } from "./wallet_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service warican.api.wallet.Wallet
 */
export const Wallet = {
  typeName: "warican.api.wallet.Wallet",
  methods: {
    /**
     * @generated from rpc warican.api.wallet.Wallet.DepositV1
     */
    depositV1: {
      name: "DepositV1",
      I: WalletDepositV1_Request,
      O: WalletDepositV1_Response,
      kind: MethodKind.Unary,
    },
  }
} as const;

