// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file wallet/wallet.proto (package warican.api.wallet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message warican.api.wallet.WalletDepositV1
 */
export class WalletDepositV1 extends Message<WalletDepositV1> {
  constructor(data?: PartialMessage<WalletDepositV1>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "warican.api.wallet.WalletDepositV1";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WalletDepositV1 {
    return new WalletDepositV1().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WalletDepositV1 {
    return new WalletDepositV1().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WalletDepositV1 {
    return new WalletDepositV1().fromJsonString(jsonString, options);
  }

  static equals(a: WalletDepositV1 | PlainMessage<WalletDepositV1> | undefined, b: WalletDepositV1 | PlainMessage<WalletDepositV1> | undefined): boolean {
    return proto3.util.equals(WalletDepositV1, a, b);
  }
}

/**
 * @generated from message warican.api.wallet.WalletDepositV1.Request
 */
export class WalletDepositV1_Request extends Message<WalletDepositV1_Request> {
  /**
   * @generated from field: fixed64 amount = 2;
   */
  amount = protoInt64.zero;

  constructor(data?: PartialMessage<WalletDepositV1_Request>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "warican.api.wallet.WalletDepositV1.Request";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "amount", kind: "scalar", T: 6 /* ScalarType.FIXED64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WalletDepositV1_Request {
    return new WalletDepositV1_Request().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WalletDepositV1_Request {
    return new WalletDepositV1_Request().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WalletDepositV1_Request {
    return new WalletDepositV1_Request().fromJsonString(jsonString, options);
  }

  static equals(a: WalletDepositV1_Request | PlainMessage<WalletDepositV1_Request> | undefined, b: WalletDepositV1_Request | PlainMessage<WalletDepositV1_Request> | undefined): boolean {
    return proto3.util.equals(WalletDepositV1_Request, a, b);
  }
}

/**
 * @generated from message warican.api.wallet.WalletDepositV1.Response
 */
export class WalletDepositV1_Response extends Message<WalletDepositV1_Response> {
  /**
   * @generated from field: warican.api.wallet.WalletDepositV1.Wallet wallet = 1;
   */
  wallet?: WalletDepositV1_Wallet;

  constructor(data?: PartialMessage<WalletDepositV1_Response>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "warican.api.wallet.WalletDepositV1.Response";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "wallet", kind: "message", T: WalletDepositV1_Wallet },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WalletDepositV1_Response {
    return new WalletDepositV1_Response().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WalletDepositV1_Response {
    return new WalletDepositV1_Response().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WalletDepositV1_Response {
    return new WalletDepositV1_Response().fromJsonString(jsonString, options);
  }

  static equals(a: WalletDepositV1_Response | PlainMessage<WalletDepositV1_Response> | undefined, b: WalletDepositV1_Response | PlainMessage<WalletDepositV1_Response> | undefined): boolean {
    return proto3.util.equals(WalletDepositV1_Response, a, b);
  }
}

/**
 * @generated from message warican.api.wallet.WalletDepositV1.Wallet
 */
export class WalletDepositV1_Wallet extends Message<WalletDepositV1_Wallet> {
  /**
   * @generated from field: fixed64 amount = 1;
   */
  amount = protoInt64.zero;

  constructor(data?: PartialMessage<WalletDepositV1_Wallet>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "warican.api.wallet.WalletDepositV1.Wallet";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "amount", kind: "scalar", T: 6 /* ScalarType.FIXED64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WalletDepositV1_Wallet {
    return new WalletDepositV1_Wallet().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WalletDepositV1_Wallet {
    return new WalletDepositV1_Wallet().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WalletDepositV1_Wallet {
    return new WalletDepositV1_Wallet().fromJsonString(jsonString, options);
  }

  static equals(a: WalletDepositV1_Wallet | PlainMessage<WalletDepositV1_Wallet> | undefined, b: WalletDepositV1_Wallet | PlainMessage<WalletDepositV1_Wallet> | undefined): boolean {
    return proto3.util.equals(WalletDepositV1_Wallet, a, b);
  }
}

