// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts"
// @generated from file wallet/wallet.proto (package warican.api.wallet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { WalletDepositV1_Request, WalletDepositV1_Response, WalletGetV1_Response } from "./wallet_pb.js";

/**
 * @generated from rpc warican.api.wallet.Wallet.DepositV1
 */
export const depositV1 = {
  localName: "depositV1",
  name: "DepositV1",
  kind: MethodKind.Unary,
  I: WalletDepositV1_Request,
  O: WalletDepositV1_Response,
  service: {
    typeName: "warican.api.wallet.Wallet"
  }
} as const;

/**
 * @generated from rpc warican.api.wallet.Wallet.GetV1
 */
export const getV1 = {
  localName: "getV1",
  name: "GetV1",
  kind: MethodKind.Unary,
  I: Empty,
  O: WalletGetV1_Response,
  service: {
    typeName: "warican.api.wallet.Wallet"
  }
} as const;
