// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: common/split-billing.proto

package commonModel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SplitBillingModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GroupId          string `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Amount           int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AdvancePayerId   string `protobuf:"bytes,5,opt,name=advance_payer_id,json=advancePayerId,proto3" json:"advance_payer_id,omitempty"`
	SplitBillingType string `protobuf:"bytes,6,opt,name=split_billing_type,json=splitBillingType,proto3" json:"split_billing_type,omitempty"`
	Status           string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SplitBillingModel) Reset() {
	*x = SplitBillingModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_split_billing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitBillingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitBillingModel) ProtoMessage() {}

func (x *SplitBillingModel) ProtoReflect() protoreflect.Message {
	mi := &file_common_split_billing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitBillingModel.ProtoReflect.Descriptor instead.
func (*SplitBillingModel) Descriptor() ([]byte, []int) {
	return file_common_split_billing_proto_rawDescGZIP(), []int{0}
}

func (x *SplitBillingModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SplitBillingModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SplitBillingModel) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SplitBillingModel) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SplitBillingModel) GetAdvancePayerId() string {
	if x != nil {
		return x.AdvancePayerId
	}
	return ""
}

func (x *SplitBillingModel) GetSplitBillingType() string {
	if x != nil {
		return x.SplitBillingType
	}
	return ""
}

func (x *SplitBillingModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_common_split_billing_proto protoreflect.FileDescriptor

var file_common_split_billing_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x2d, 0x62,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0xda, 0x01, 0x0a, 0x11, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x42, 0x69,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x64, 0x76,
	0x61, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x73,
	0x70, 0x6c, 0x69, 0x74, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x42, 0x69,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x43, 0x69, 0x74, 0x79, 0x42, 0x65, 0x61, 0x72, 0x33, 0x2f, 0x57, 0x61, 0x72, 0x69, 0x43, 0x61,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_split_billing_proto_rawDescOnce sync.Once
	file_common_split_billing_proto_rawDescData = file_common_split_billing_proto_rawDesc
)

func file_common_split_billing_proto_rawDescGZIP() []byte {
	file_common_split_billing_proto_rawDescOnce.Do(func() {
		file_common_split_billing_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_split_billing_proto_rawDescData)
	})
	return file_common_split_billing_proto_rawDescData
}

var file_common_split_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_split_billing_proto_goTypes = []any{
	(*SplitBillingModel)(nil), // 0: common.SplitBillingModel
}
var file_common_split_billing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_split_billing_proto_init() }
func file_common_split_billing_proto_init() {
	if File_common_split_billing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_split_billing_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SplitBillingModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_split_billing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_split_billing_proto_goTypes,
		DependencyIndexes: file_common_split_billing_proto_depIdxs,
		MessageInfos:      file_common_split_billing_proto_msgTypes,
	}.Build()
	File_common_split_billing_proto = out.File
	file_common_split_billing_proto_rawDesc = nil
	file_common_split_billing_proto_goTypes = nil
	file_common_split_billing_proto_depIdxs = nil
}
