// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package dao

import (
	"context"

	"github.com/google/uuid"
)

const getUserByUID = `-- name: GetUserByUID :one
SELECT distinct id, uid, email, first_name, last_name, created_at, updated_at
FROM "user"
WHERE "uid" = $1
`

// :param uid uuid
func (q *Queries) GetUserByUID(ctx context.Context, uid uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUID, uid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
