// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts"
// @generated from file group/group.proto (package warican.api.group, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { GroupCreateV1_Request, GroupCreateV1_Response, GroupGetV1_Request, GroupGetV1_Response } from "./group_pb.js";

/**
 * @generated from rpc warican.api.group.Group.CreateV1
 */
export const createV1 = {
  localName: "createV1",
  name: "CreateV1",
  kind: MethodKind.Unary,
  I: GroupCreateV1_Request,
  O: GroupCreateV1_Response,
  service: {
    typeName: "warican.api.group.Group"
  }
} as const;

/**
 * @generated from rpc warican.api.group.Group.GetV1
 */
export const getV1 = {
  localName: "getV1",
  name: "GetV1",
  kind: MethodKind.Unary,
  I: GroupGetV1_Request,
  O: GroupGetV1_Response,
  service: {
    typeName: "warican.api.group.Group"
  }
} as const;
