name: cd-api
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: 'latest'
          install_components: 'beta'
      - name: 'Configure Docker'
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev
      - name: 'Build Docker Image (api)'
        run: docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/warican-api:${{ github.sha }} ./backend
      - name: 'Push Docker Image (api)'
        run: docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/warican-api:${{ github.sha }}
      - name: 'Deploy to Cloud Run (api)'
        run: >
          gcloud beta run deploy warican-api
          --image ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/warican-api:${{ github.sha }}
          --region ${{ secrets.REGION }}
          --service-account ${{ secrets.RUN_API_SERVICE_ACCOUNT }}
          --platform managed --region ${{ secrets.REGION }}
          --allow-unauthenticated
          --service-min-instances 0
          --max-instances 2
          --memory 1Gi
          --cpu 1
          --port 8080
          --use-http2
          --add-cloudsql-instances ${{ secrets.CLOUD_SQL_INSTANCE_NAME }}
          --update-env-vars DB_HOST=${{ secrets.DB_HOST }}
          --update-env-vars IS_DEVELOPMENT=true
          --update-secrets DB_USER=DB_USER:latest
          --update-secrets DB_PASSWORD=DB_PASSWORD:latest
          --update-secrets DB_NAME=DB_NAME:latest
          --revision-suffix ${{ github.sha }}
#      - name: 'Build Docker Image (ui)'
#        run: docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/warican-ui:${{ github.sha }} ./frontend
#      - name: 'Push Docker Image (ui)'
#        run: docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/warican-ui:${{ github.sha }}
#      - name: 'Deploy to Cloud Run (ui)'
#        run: >
#          gcloud beta run deploy warican-ui
#          --image ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/warican-ui:${{ github.sha }}
#          --region ${{ secrets.REGION }}
#          --service-account ${{ secrets.RUN_UI_SERVICE_ACCOUNT }}
#          --platform managed --region ${{ secrets.REGION }}
#          --allow-unauthenticated
#          --service-min-instances 0
#          --max-instances 2
#          --memory 512Mi
#          --cpu 1
#          --port 3000
#          --update-secrets NEXT_PUBLIC_DEVELOPMENT_USER=DEV_USER:latest
#          --revision-suffix ${{ github.sha }}
